# Environment

In [74]:
# import sys
# from pathlib import Path
# from sklearn.linear_model import LinearRegression
import pulp
from sklearn.neighbors import NearestNeighbors

from sqlalchemy import create_engine, text
import pandas as pd
import geopandas as gpd
import numpy as np

# Data

In [2]:
DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

In [6]:
uplifts_df = pd.read_sql("SELECT * FROM results.uplifts ", engine)
models_df = pd.read_sql("SELECT * FROM results.models ", engine)
pred_reg_prices_df = pd.read_sql("SELECT * FROM results.predicted_reg_prices ", engine)
urban_blocks_ng = pd.read_sql(
    'SELECT * FROM core.urban_blocks',
    engine
)
urban_blocks = gpd.read_postgis(
    'SELECT * FROM core.urban_blocks_geom',
    engine,
    geom_col='geometry'
)

# Functions

In [71]:
def calculate_effect_significance(df, columns_list):
    df_arg = df.copy()
    
    output = []

    for col in columns_list:
        series = df_arg[col].dropna()

        att = series.mean()

        se = series.std(ddof=1) / np.sqrt(len(series))

        ci_low = att - 1.96 * se
        ci_high = att + 1.96 * se

        is_significant = (ci_low > 0) or (ci_high < 0)

        output.append({
            "model": col,
            "ci_low": ci_low,
            "att": att,
            "ci_high": ci_high,
            "is_significant": is_significant
        })

    return pd.DataFrame(output)

In [8]:
import folium
import branca.colormap as cm
import webbrowser
from tempfile import NamedTemporaryFile

def show_map(
    gdf,
    value_col,
    geometry_col="geometry",
    cmap="blue",
    tiles="CartoDB positron",
    opacity=0.8,
):
    """
    Wyświetla interaktywną mapę GeoDataFrame w przeglądarce.

    Parameters
    ----------
    gdf : GeoDataFrame
        Dane przestrzenne.
    value_col : str
        Kolumna używana do kolorowania.
    geometry_col : str
        Nazwa kolumny geometrii.
    cmap : str
        "blue", "red", "yellow", "grey",
        "green", "purple", "brown"
    tiles : str
        Podkład mapy Folium.
    opacity : float
        Przezroczystość poligonów.
    """

    # Kolory prezentacyjne
    colors = {
        "blue":   (2, 87, 163),
        "red":    (227, 26, 28),
        "yellow": (224, 184, 24),
        "grey":   (210, 214, 216),
        "green":  (27, 158, 119),
        "purple": (117, 107, 177),
        "brown":  (140, 81, 10),
    }

    if cmap not in colors:
        raise ValueError(f"Nieznana paleta '{cmap}'.")

    gdf = gdf.copy()

    if geometry_col != gdf.geometry.name:
        gdf = gdf.set_geometry(geometry_col)

    # Folium wymaga WGS84
    if gdf.crs is not None and gdf.crs.to_epsg() != 4326:
        gdf = gdf.to_crs(4326)

    # Środek mapy
    center = gdf.unary_union.centroid
    m = folium.Map(
        location=[center.y, center.x],
        zoom_start=13,
        tiles=tiles
    )

    rgb = colors[cmap]
    color_hex = "#{:02x}{:02x}{:02x}".format(*rgb)

    colormap = cm.LinearColormap(
        colors=["white", color_hex],
        vmin=gdf[value_col].min(),
        vmax=gdf[value_col].max(),
    )

    def style_function(feature):
        value = feature["properties"][value_col]

        if value is None:
            fill = "#FFFFFF"
        else:
            fill = colormap(value)

        return {
            "fillColor": fill,
            "color": "black",
            "weight": 0.5,
            "fillOpacity": opacity,
        }

    folium.GeoJson(
        gdf,
        style_function=style_function,
        tooltip=folium.GeoJsonTooltip(
            fields=[value_col],
            aliases=[value_col]
        ),
    ).add_to(m)

    colormap.caption = value_col
    colormap.add_to(m)

    # Wyświetlenie bez ręcznego zapisywania pliku
    with NamedTemporaryFile("w", suffix=".html", delete=False, encoding="utf-8") as f:
        m.save(f.name)
        webbrowser.open("file://" + f.name)

    return m

# Input

In [24]:
list_of_the_uplifts = ['urVibBlPr_coun_00000000', 'urVibSCBx_coun_00000000',
       'socVrEduc_avrg_00000000']
latest_uplifts = True
post_period = 2025

# Data preparation

In [20]:
list_of_models = (
    models_df[
        models_df['target_id'].isin(list_of_the_uplifts)
    ]
    .sort_values('run_at')
    .drop_duplicates('target_id', keep='last')
)['model_id'].unique().tolist()

In [79]:
models_dict = (
    models_df[
        models_df['target_id'].isin(list_of_the_uplifts)
    ]
    .sort_values('run_at')
    .drop_duplicates('target_id', keep='last')
    .set_index('model_id')['target_id']
    .to_dict()
)

In [60]:
dict_of_block_id_counts = uplifts_df[
    uplifts_df['model_id'].isin(
        list_of_models)]['model_id'].value_counts().to_dict()
min_key_block_id_counts = min(dict_of_block_id_counts, key=dict_of_block_id_counts.get)
list_of_min_set_of_block_id = uplifts_df[
    uplifts_df['model_id'] == min_key_block_id_counts]['block_id'].unique().tolist()

In [61]:
urban_blocks_ng_post = urban_blocks_ng[(urban_blocks_ng[
    'year']==pd.Timestamp(f'{post_period}-01-01'))
    &(urban_blocks_ng[
    'block_id'].isin(list_of_min_set_of_block_id))
    ].reset_index(drop=True).copy()
urban_blocks_d1nq = urban_blocks_ng_post[urban_blocks_ng_post['treated_d1nq'] == 1]['block_id'].unique().tolist()
urban_blocks_1nq = urban_blocks_ng_post[urban_blocks_ng_post['treated_1nq'] == 1]['block_id'].unique().tolist()

In [62]:
sel_uplifts_df = uplifts_df[uplifts_df['model_id'].isin(list_of_models)]
sel_uplifts_df_to_check_sign_d1nq = sel_uplifts_df[
    (sel_uplifts_df['block_id'].isin(urban_blocks_d1nq))
    &(sel_uplifts_df['treatment'] == 'd1nq')].copy()
sel_uplifts_df_to_check_sign_1nq = sel_uplifts_df[
    (sel_uplifts_df['block_id'].isin(urban_blocks_1nq))
    &(sel_uplifts_df['treatment'] == '1nq')].copy()

In [66]:
sel_uplifts_df_to_check_sign_1nq2 = sel_uplifts_df_to_check_sign_1nq.pivot(
    index='block_id',
    columns='model_id',
    values='uplift',
).reset_index()
sel_uplifts_df_to_check_sign_d1nq2 = sel_uplifts_df_to_check_sign_d1nq.pivot(
    index='block_id',
    columns='model_id',
    values='uplift',
).reset_index()

In [84]:
sign_upl_d1nq2 = calculate_effect_significance(
    sel_uplifts_df_to_check_sign_d1nq2, list_of_models)
sign_upl_d1nq2['treatment'] = 'd1nq'
sign_upl_1nq2 =calculate_effect_significance(
    sel_uplifts_df_to_check_sign_1nq2, list_of_models)
sign_upl_1nq2['treatment'] = '1nq'
sign_upl = pd.concat([sign_upl_d1nq2, sign_upl_1nq2])[
    ['model','treatment', 'ci_low', 'att', 'ci_high', 'is_significant']].reset_index(
        drop=True).copy()
sign_upl = sign_upl[sign_upl['is_significant'] == True]
sign_upl

           model treatment    ci_low       att   ci_high  is_significant
0  CF00000000001      d1nq  0.411975  0.468214  0.524453            True
2  CF00000000003      d1nq  0.137814  0.137814  0.137814            True
3  CF00000000001       1nq  0.882007  0.935299  0.988592            True
4  CF00000000002       1nq  0.655200  0.738078  0.820957            True
5  CF00000000003       1nq  0.100849  0.100849  0.100849            True

In [82]:
sign_upl_d1nq2.columns.tolist()

['model', 'ci_low', 'att', 'ci_high', 'is_significant', 'treatment']

In [ ]:
sign_upl_1nq2 =calculate_effect_significance(
    sel_uplifts_df_to_check_sign_1nq2, list_of_models)
sign_upl_1nq2['treatment'] = '1nq'

           model    ci_low       att   ci_high  is_significant
0  CF00000000001  0.882007  0.935299  0.988592            True
1  CF00000000002  0.655200  0.738078  0.820957            True
2  CF00000000003  0.100849  0.100849  0.100849            True

In [69]:
sel_uplifts_df_to_check_sign_d1nq2.columns.tolist()

['block_id', 'CF00000000001', 'CF00000000002', 'CF00000000003']

# Optimization